### ISSUE TITLE
unable to PDFbundle - sendpdf

### ISSUE THREAD

**Issue by yosefromano** [sgladstone/com.fountaintribe.scheduledcommunication#2]
I am trying to set up a scheduled job to automatically send me PDF batches. 
I can't get the staff_contact parameter to work. 
These are my parameteres
![Screen Shot 2019-09-12 at 3 44 57 PM](https://user-images.githubusercontent.com/10218159/64826050-53c73e80-d574-11e9-9549-b12da3ae0cac.png)

This is the debug info
{
"error_code": 0,
"entity": "PDFbundle",
"action": "sendpdf",
"trace": "#0 /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(101): civicrm_api3_p_d_fbundle_Sendpdf(Array)\n#1 ,
 /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/Civi/API/Kernel.php(168): Civi\\API\\Provider\\MagicFunctionProvider->invoke(Array)\n#2 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/Civi/API/Kernel.php(99): Civi\\API\\Kernel->runRequest(Array)\n#3 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/api/api.php(23): Civi\\API\\Kernel->runSafe('PDFbundle', 'sendpdf', Array, NULL)\n#4 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/CRM/Utils/REST.php(316): civicrm_api('PDFbundle', 'sendpdf', Array)\n#5 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/CRM/Utils/REST.php(566): CRM_Utils_REST::process(Array, Array)\n#6 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/CRM/Core/Invoke.php(277): CRM_Utils_REST::ajax()\n#7 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/CRM/Core/Invoke.php(85): CRM_Core_Invoke::runItem(Array)\n#8 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke(Array)\n#9 , /var/aegir/platforms/chabadsuite/sites/all/modules/civicrm/drupal/civicrm.module(444): CRM_Core_Invoke::invoke(Array)\n#10 , /var/aegir/platforms/chabadsuite/includes/menu.inc(527): civicrm_invoke('ajax', 'rest')\n#11 , /var/aegir/platforms/chabadsuite/index.php(21): menu_execute_active_handler()\n#12 , {main}",
    "is_error": 1,
    "error_message": "Error sending e-mail to "
}

**Comment by sgladstone** [comment]
Please add "to_email" as a parameter to the scheduled job.  

Such as:
to_email=someone@example.org

**Comment by yosefromano** [comment]
I added the parameter and this allowed the Job to run and I received an email with the attached PDF, however, the PDF was blank...

I double-checked that there were contacts in the group and that I can successfully manually generate letters for these contacts using the same template. 

Only error I see is in the watchdog
Warning: implode(): Invalid arguments passed in civicrm_api3_p_d_fbundle_Sendpdf() (line 148 of /var/aegir/platforms/chabadsuite/profiles/chabadsuite/extensions/com.fountaintribe.scheduledcommunication/api/v3/PDFbundle/Sendpdf.php).

Also, if we have to add the email_to parameter, why is the staff_contact one needed? Seems redundant. The email_to parameter makes it easier to setup since you don't have to lookup the contact's id...

**Comment by yosefromano** [comment]
@sgladstone any thoughts?
